### ISSUE TITLE
Watch non-Maven central repos

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/dependency-watch#8]
Probably switch to TOML to support this:
```toml
[mavenCentral]
coordinates = [
  "whevs:whevs",
  "foo:bar",
]

[googleMaven]
coordinates = [
  "stuff:stuff",
]

[myCustom]
name = "My Custom"
host = "https://my.custom.repo/"
coordinates = [
  "secret:stuff",
]
```
